### ISSUE TITLE
engine.js#validateMeasurements() needs to be adapted to support location telemetry

### ISSUE THREAD

**Issue by kartben** [Azure/iotc-device-bridge#25]
As the title indicates: if location measurements are sent to the device bridge, they cause validateMeasurements() to return false as a location is not a "simple" telemetry, i.e neither a JS 'number' nor a 'string'.

**Comment by peolivei2** [comment]
Thanks for reporting it. I'll make this change.

**Comment by kartben** [comment]
FWIW I wonder if validating the measurements really brings value in the end? Should the payload be somehow invalid the bridge can surface any potential error Central might thrown as an HTTP error?

**Comment by peolivei2** [comment]
device-bridge talks directly to IotHub, which will accept any data you send. So, this validation is the only way to warn users that something is wrong with theie payload format.

**Comment by kartben** [comment]
Sure but my point is more that the quick sanity check that
validateMeasurements perform is not necessarily enough -- for example it
will let people publish a state as a number, which can cause issues further
down the road in IoTC. I think checking that the payload is a valid JSON
document could be enough, doing more would require to know about the
template/model in order to really provide a meaningful check.

**Comment by peolivei2** [comment]
The payload will always be valid JSON, as it comes directly from the request body of the function.
The goal of this check is not to make sure that the data conforms to the template, but to avoid simple integration problems. For instance, it will ensure that the incoming payload is a flat object, unless for for specific types like location.
From what we've seen by the issues reported here and the ones sent through email, this has avoided problems on integrations like TTN and Particle, where users sometimes don't format things properly in the webhook configuration of these services. In these cases, the user can easily see a 400 in their logs rather than just a silent failure.
