### ISSUE TITLE
Using device bridge for high-volumes

### ISSUE THREAD

**Issue by andrewschmidt-a** [Azure/iotc-device-bridge#36]
Hi I am working at 3M and we have a product that involves a DPS and IotHub we are interested in using this repo for. I have stood it up and tested it out using a DPS and IoTHub that are not in IoTCentral. From initial testing I have already hit registration limits. 

My understanding is that the function does the following:

incoming payload --> enroll device in DPS --> simulate telemetry to IoT Hub

So one thing we want to do to modify this is to allow a batch upload. I was thinking we could create another function that splits it and then sticks it in a ServiceBusQueue to control the volume of data going into the bridge function

Batch Payload --> Splitting function --> SB Queue  --> Device Bridge function --> IotHub

Is my current understanding of the limitations or use case of this repo incorrect? It doesnt seem like it would be capable of registering new devices at the frequency of high volumes of requests.

**Comment by peolivei2** [comment]
The code uses local in memory cache for devices registration, so a device is only registered in DPS if it hasn't been seen by the Azure function in the past. After that all messages are sent directly to hub bypassing the registration. The registration limit itself is [set by DPS](https://docs.microsoft.com/en-us/azure/iot-dps/about-iot-dps#quotas).

**Comment by andrewschmidt-a** [comment]
So what you are saying is that if the function is fanning out to multiple instances it will likely be attempting to re-register for the same device, which could cause a DPS registration limit to be hit? 

We are seeing this limit while using the same device name, so im worried cause we arent even scaling it out to more than one device to use the bridge and its causing us issues.

**Comment by andrewschmidt-a** [comment]
I guess my question would be better phrased. Does this bridge intend for high-volumes of data?

**Comment by peolivei2** [comment]
The solution deployed here uses a consumption plan by default, which usually uses no more than a few instances (in fact, a dedicated standard consumption plan will use no more than 10 instances when fully scaled). So it's very unlikely that you'd reach registration limits due to different instances unless your solution is using a really big function plan or a large number of devices with different device IDs calling in the first minute (but you mentioned that you're having problems even with a single device, so this is likely not the case).

The code itself doesn't allow the same device to send more than [one registration request per minute](https://github.com/Azure/iotc-device-bridge/blob/master/IoTCIntegration/lib/engine.js#L101). If that happens, you'll get a log saying `Unable to register device ${deviceId}. Minimum registration timeout not yet exceeded. Please try again in ${backoff} seconds`, which comes from the function itself, not from DPS. This message will only stop appearing when the first registration attempt succeeds. Is this the error message you are seeing?
